#:tombi toml-version = "v1.0.0"

allow-comparison-to-zero = false
allow-exact-repetitions = false
allow-expect-in-consts = false
allow-large-stack-frames-in-tests = false
allow-mixed-uninlined-format-args = false
allow-unwrap-in-consts = false
allow-unwrap-in-tests = true
avoid-breaking-exported-api = false
upper-case-acronyms-aggressive = true

absolute-paths-allowed-crates = ["build_rs", "proc_exit"]
allowed-idents-below-min-chars = ["e", ".."]
disallowed-macros = [
    "core::panic",
    "core::todo",
    "core::unimplemented",
    "core::unreachable",
]
disallowed-methods = [
    "core::hint::assert_unchecked",
    "core::hint::unreachable_unchecked",
    "std::fs::metadata",
    "std::panic::panic_any",
    "std::panic::resume_unwind",
    "std::process::abort",
    "std::process::exit",
    "tokio::fs::metadata",
]
disallowed-names = ["foobar", "bar", "qux", ".."]
