#:tombi toml-version = "v1.0.0"

allow-comparison-to-zero = false
allow-exact-repetitions = false
allow-expect-in-consts = false
allow-large-stack-frames-in-tests = false
allow-mixed-uninlined-format-args = false
allow-unwrap-in-consts = false
avoid-breaking-exported-api = false

absolute-paths-allowed-crates = ["build_rs", "proc_exit", "tracing_subscriber"]
disallowed-macros = [
    "std::panic",
    "std::todo",
    "std::unimplemented",
    "std::unreachable",
]
disallowed-methods = [
    "std::panic::panic_any",
    "std::panic::resume_unwind",
    "std::process::abort",
    "std::process::exit",
]
