#:schema https://www.schemastore.org/rust-toolchain.json

[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-src"]
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
]
profile = "minimal"
