#:schema https://www.schemastore.org/taplo.json

include = ["**/*.toml"]
exclude = ["target/**"]

[formatting]
indent_string = "    "
allowed_blank_lines = 1

[[rule]]
include = ["**/Cargo.toml"]
keys = [
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
    "target.*.dependencies",
    "target.*.dev-dependencies",
    "target.*.build-dependencies",
]

[rule.formatting]
inline_table_expand = false
reorder_keys = true
reorder_arrays = true
