pub(crate) mod codename;
#[cfg(target_os = "macos")]
pub(crate) mod codesign;
#[cfg(target_os = "macos")]
pub(crate) mod mach_o;
#[cfg(target_os = "macos")]
pub(crate) mod tag;
#[cfg(target_os = "macos")]
pub(crate) mod xcode;
