#:tombi toml-version = "v1.1.0"

[unstable]
cargo-lints = true

[build]
target = "host-tuple"

[env]
RUST_BACKTRACE = "1"
RUSTC_ICE = "0"

[target.'cfg(all())']
rustflags = ["--cfg=tokio_unstable"]
rustdocflags = ["--cfg=tokio_unstable"]
