#:schema https://mise.jdx.dev/schema/mise.json

[settings]
disable_hints = ["*"]
unix_default_file_shell_args = "/bin/sh -eu --"
unix_default_inline_shell_args = "/bin/sh -c -eu --"
task.output = "keep-order"

# Setup Task

[tasks.setup]
run = "brew bundle check || brew bundle install"

# Grouped Tasks

[tasks.format]
depends = ["format:**"]

[tasks.lint]
depends = ["lint:**"]

[tasks.fix]
depends = ["fix:**"]

[tasks.test]
depends = ["test:**"]

[tasks.build]
depends = ["build:**"]

# Cargo Tasks

[tasks."cargo:run"]
run = "cargo +nightly run"

[tasks."cargo:fmt"]
run = "cargo +nightly fmt"
alias = "format:rustfmt"

[tasks."cargo:fmt:check"]
run = "cargo +nightly fmt -- --check"
alias = "lint:rustfmt"

[tasks."cargo:check"]
run = "cargo +nightly check"

[tasks."cargo:check:fix"]
run = "cargo +nightly fix"

[tasks."cargo:clippy"]
run = "cargo +nightly clippy"
alias = "lint:clippy"

[tasks."cargo:clippy:fix"]
run = "cargo +nightly clippy --fix"
alias = "fix:clippy"

[tasks."cargo:test"]
run = "cargo +nightly test"

[tasks."cargo:nextest"]
run = "cargo +nightly nextest run --no-tests=\"pass\""
alias = "test:nextest"

[tasks."cargo:doctest"]
run = "cargo +nightly test --doc"
alias = "test:doctest"

[tasks."cargo:doc"]
run = "cargo +nightly doc --no-deps"

[tasks."cargo:build"]
run = "cargo build --release"
alias = "build:rustc"

[tasks."cargo:bench"]
run = "cargo bench"

# Other Tasks

[tasks."format:taplo"]
run = "RUST_LOG=\"error\" taplo fmt"

[tasks."lint:taplo:fmt"]
run = "RUST_LOG=\"error\" taplo fmt --diff --check"

[tasks."lint:taplo:check"]
run = "RUST_LOG=\"error\" taplo check --default-schema-catalogs"

[tasks."lint:markdownlint"]
run = "markdownlint-cli2 \"**/*.md\" \"#.git\" \"#.vscode/mise-tools\" \"#target\""

[tasks."fix:markdownlint"]
run = "markdownlint-cli2 \"**/*.md\" \"#.git\" \"#.vscode/mise-tools\" \"#target\" --fix"

[tasks."format:prettier"]
run = "prettier \"**/*.{md,yaml,yml}\" --no-error-on-unmatched-pattern --check --write"

[tasks."lint:prettier"]
run = "prettier \"**/*.{md,yaml,yml}\" --no-error-on-unmatched-pattern --check"

[tasks."format:biome"]
run = "biome format --no-errors-on-unmatched --write"

[tasks."lint:biome:format"]
run = "biome format --no-errors-on-unmatched"

[tasks."lint:biome:lint"]
run = "biome lint --no-errors-on-unmatched"

[tasks."fix:biome:safe"]
run = "biome lint --no-errors-on-unmatched --write"

[tasks."fix:biome:unsafe"]
run = "biome lint --no-errors-on-unmatched --unsafe"

[tasks."format:shfmt"]
run = "shfmt --list --write \".\""

[tasks."lint:shfmt"]
run = "shfmt --list --diff \".\""

[tasks."lint:shellcheck"]
run = "shfmt --find=0 \".\" | xargs -r -0 shellcheck"

[tasks."fix:shellcheck"]
run = "shfmt --find=0 \".\" | xargs -r -0 shellcheck --format=\"diff\" | patch -p1"

[tasks."lint:cspell:lint"]
run = "cspell \".\" --no-must-find-files --no-progress --show-suggestions --show-context"

[tasks."lint:cspell:dictionaries"]
shell = "/bin/sh -eu --"
run = ".mise/scripts/lint-cspell-dictionaries.sh"
