# $schema: https://www.schemastore.org/github-workflow.json

name: Rust Workflow

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

defaults:
  run:
    shell: /bin/sh -eu -- "{0}"

jobs:
  lint:
    uses: ./.github/workflows/reusable.yml
    with:
      task: lint

  fix:
    uses: ./.github/workflows/reusable.yml
    with:
      task: fix

  test:
    uses: ./.github/workflows/reusable.yml
    with:
      task: test

  doc:
    uses: ./.github/workflows/reusable.yml
    with:
      task: doc

  build:
    uses: ./.github/workflows/reusable.yml
    with:
      task: build

  bench:
    uses: ./.github/workflows/reusable.yml
    with:
      task: bench
