# $schema: https://www.schemastore.org/github-workflow.json

name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/reusable.yml
    with:
      task: test

  build:
    uses: ./.github/workflows/reusable.yml
    with:
      task: build
      # cache: false
